//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoAcaoCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pa_Acao
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public Nullable<int> Unidade_Id { get; set; }
        public Nullable<int> Departamento_Id { get; set; }
        public Nullable<System.DateTime> QuandoInicio { get; set; }
        public Nullable<int> DuracaoDias { get; set; }
        public Nullable<System.DateTime> QuandoFim { get; set; }
        public string ComoPontosimportantes { get; set; }
        public Nullable<int> Predecessora_Id { get; set; }
        public string PraQue { get; set; }
        public Nullable<decimal> QuantoCusta { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Panejamento_Id { get; set; }
    
        public virtual Pa_Planejamento Pa_Planejamento { get; set; }
    }
}
