//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesPA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanoDeAcaoMVC.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string _new {
            get {
                return ResourceManager.GetString("_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string _return {
            get {
                return ResourceManager.GetString("_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompaniment.
        /// </summary>
        public static string accompaniment {
            get {
                return ResourceManager.GetString("accompaniment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompaniment of the Action.
        /// </summary>
        public static string accompaniment_action {
            get {
                return ResourceManager.GetString("accompaniment_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string action_name {
            get {
                return ResourceManager.GetString("action_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action plan.
        /// </summary>
        public static string action_plan {
            get {
                return ResourceManager.GetString("action_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active:.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string active2 {
            get {
                return ResourceManager.GetString("active2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        public static string active3 {
            get {
                return ResourceManager.GetString("active3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action.
        /// </summary>
        public static string add_action {
            get {
                return ResourceManager.GetString("add_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressee.
        /// </summary>
        public static string addressee {
            get {
                return ResourceManager.GetString("addressee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Plannings to Filter.
        /// </summary>
        public static string all_plannings_to_filter {
            get {
                return ResourceManager.GetString("all_plannings_to_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL TASKS TO FILTER.
        /// </summary>
        public static string all_tasks_filter {
            get {
                return ResourceManager.GetString("all_tasks_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks to filter.
        /// </summary>
        public static string all_tasks_to_filter {
            get {
                return ResourceManager.GetString("all_tasks_to_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string all2 {
            get {
                return ResourceManager.GetString("all2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical order.
        /// </summary>
        public static string alphabetical_order {
            get {
                return ResourceManager.GetString("alphabetical_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string apr {
            get {
                return ResourceManager.GetString("apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string apr2 {
            get {
                return ResourceManager.GetString("apr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Important Points.
        /// </summary>
        public static string as_important_points {
            get {
                return ResourceManager.GetString("as_important_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string aug {
            get {
                return ResourceManager.GetString("aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string aug2 {
            get {
                return ResourceManager.GetString("aug2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By GRJ Solutions.
        /// </summary>
        public static string by_grj_solutions {
            get {
                return ResourceManager.GetString("by_grj_solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY STATUS.
        /// </summary>
        public static string by_status {
            get {
                return ResourceManager.GetString("by_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string canceled {
            get {
                return ResourceManager.GetString("canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change planning.
        /// </summary>
        public static string change_planning {
            get {
                return ResourceManager.GetString("change_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Strategic Link.
        /// </summary>
        public static string change_strategic_link {
            get {
                return ResourceManager.GetString("change_strategic_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tactical Link.
        /// </summary>
        public static string change_tactical_link {
            get {
                return ResourceManager.GetString("change_tactical_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns have been saved successfully!.
        /// </summary>
        public static string columns_saved_successfully {
            get {
                return ResourceManager.GetString("columns_saved_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative.
        /// </summary>
        public static string comparative {
            get {
                return ResourceManager.GetString("comparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed late.
        /// </summary>
        public static string completed_late {
            get {
                return ResourceManager.GetString("completed_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Tasks.
        /// </summary>
        public static string completed_tasks {
            get {
                return ResourceManager.GetString("completed_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordination.
        /// </summary>
        public static string coordination {
            get {
                return ResourceManager.GetString("coordination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save record:.
        /// </summary>
        public static string could_not_save_record {
            get {
                return ResourceManager.GetString("could_not_save_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string creation_date {
            get {
                return ResourceManager.GetString("creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current View.
        /// </summary>
        public static string current_view {
            get {
                return ResourceManager.GetString("current_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized.
        /// </summary>
        public static string customized {
            get {
                return ResourceManager.GetString("customized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the conclusion.
        /// </summary>
        public static string date_conclusion {
            get {
                return ResourceManager.GetString("date_conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project end date / Initiative.
        /// </summary>
        public static string date_end_project_initiative {
            get {
                return ResourceManager.GetString("date_end_project_initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of delay.
        /// </summary>
        public static string days_of_delay {
            get {
                return ResourceManager.GetString("days_of_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string dec {
            get {
                return ResourceManager.GetString("dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string dec2 {
            get {
                return ResourceManager.GetString("dec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed Tasks.
        /// </summary>
        public static string delayed_tasks {
            get {
                return ResourceManager.GetString("delayed_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Action.
        /// </summary>
        public static string delete_action {
            get {
                return ResourceManager.GetString("delete_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string delivery {
            get {
                return ResourceManager.GetString("delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVIATION ANALYSIS REPORT.
        /// </summary>
        public static string deviation_analysis_report {
            get {
                return ResourceManager.GetString("deviation_analysis_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string dimension {
            get {
                return ResourceManager.GetString("dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorship.
        /// </summary>
        public static string directorship {
            get {
                return ResourceManager.GetString("directorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Action.
        /// </summary>
        public static string edit_action {
            get {
                return ResourceManager.GetString("edit_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Planning.
        /// </summary>
        public static string edit_planning {
            get {
                return ResourceManager.GetString("edit_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial end of selected period.
        /// </summary>
        public static string end_date_selected_period {
            get {
                return ResourceManager.GetString("end_date_selected_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving!.
        /// </summary>
        public static string error_saving {
            get {
                return ResourceManager.GetString("error_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string feb {
            get {
                return ResourceManager.GetString("feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string feb2 {
            get {
                return ResourceManager.GetString("feb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields must be completed.
        /// </summary>
        public static string fields_must_be_completed {
            get {
                return ResourceManager.GetString("fields_must_be_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Filtered _MAX_ records).
        /// </summary>
        public static string filtered_max_records {
            get {
                return ResourceManager.GetString("filtered_max_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished late.
        /// </summary>
        public static string finished_late {
            get {
                return ResourceManager.GetString("finished_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For what.
        /// </summary>
        public static string for_what {
            get {
                return ResourceManager.GetString("for_what", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form of.
        /// </summary>
        public static string form_of {
            get {
                return ResourceManager.GetString("form_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMATION OF STOCKS IN ACTION.
        /// </summary>
        public static string formation_of_stocks_in_action {
            get {
                return ResourceManager.GetString("formation_of_stocks_in_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string fri {
            get {
                return ResourceManager.GetString("fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Action.
        /// </summary>
        public static string generic_action {
            get {
                return ResourceManager.GetString("generic_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERIC ACTION.
        /// </summary>
        public static string generic_action2 {
            get {
                return ResourceManager.GetString("generic_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Cause.
        /// </summary>
        public static string generic_cause {
            get {
                return ResourceManager.GetString("generic_cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERIC CAUSE.
        /// </summary>
        public static string generic_cause2 {
            get {
                return ResourceManager.GetString("generic_cause2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAL OF THE INDICATOR.
        /// </summary>
        public static string goal_indicator {
            get {
                return ResourceManager.GetString("goal_indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Cause.
        /// </summary>
        public static string group_cause {
            get {
                return ResourceManager.GetString("group_cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP CAUSE.
        /// </summary>
        public static string group_cause2 {
            get {
                return ResourceManager.GetString("group_cause2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guideline.
        /// </summary>
        public static string guideline {
            get {
                return ResourceManager.GetString("guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines.
        /// </summary>
        public static string guidelines {
            get {
                return ResourceManager.GetString("guidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How.
        /// </summary>
        public static string how {
            get {
                return ResourceManager.GetString("how", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much.
        /// </summary>
        public static string how_much {
            get {
                return ResourceManager.GetString("how_much", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string in_progress {
            get {
                return ResourceManager.GetString("in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INACTIVE.
        /// </summary>
        public static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator.
        /// </summary>
        public static string indicator {
            get {
                return ResourceManager.GetString("indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGQ Indicator .
        /// </summary>
        public static string indicator_sgq {
            get {
                return ResourceManager.GetString("indicator_sgq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Type.
        /// </summary>
        public static string indicator_type {
            get {
                return ResourceManager.GetString("indicator_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDICATORS WITH DEVICES.
        /// </summary>
        public static string indicators_devices {
            get {
                return ResourceManager.GetString("indicators_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators / Guideline.
        /// </summary>
        public static string indicators_guideline {
            get {
                return ResourceManager.GetString("indicators_guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators of the Guidelines.
        /// </summary>
        public static string indicators_guidelines {
            get {
                return ResourceManager.GetString("indicators_guidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators of the Project / Initiative.
        /// </summary>
        public static string indicators_project_initiative {
            get {
                return ResourceManager.GetString("indicators_project_initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial date of selected period.
        /// </summary>
        public static string initial_date_selected_period {
            get {
                return ResourceManager.GetString("initial_date_selected_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial View.
        /// </summary>
        public static string initial_view {
            get {
                return ResourceManager.GetString("initial_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        public static string initiative {
            get {
                return ResourceManager.GetString("initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name:.
        /// </summary>
        public static string item_name {
            get {
                return ResourceManager.GetString("item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string jan {
            get {
                return ResourceManager.GetString("jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string jan2 {
            get {
                return ResourceManager.GetString("jan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string july2 {
            get {
                return ResourceManager.GetString("july2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string june2 {
            get {
                return ResourceManager.GetString("june2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string late {
            get {
                return ResourceManager.GetString("late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string log_off {
            get {
                return ResourceManager.GetString("log_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Manage.
        /// </summary>
        public static string manage {
            get {
                return ResourceManager.GetString("manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Objective.
        /// </summary>
        public static string management_objective {
            get {
                return ResourceManager.GetString("management_objective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string mar {
            get {
                return ResourceManager.GetString("mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string mar2 {
            get {
                return ResourceManager.GetString("mar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string may2 {
            get {
                return ResourceManager.GetString("may2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MENU_ results per page.
        /// </summary>
        public static string menu_results_per_page {
            get {
                return ResourceManager.GetString("menu_results_per_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string mon {
            get {
                return ResourceManager.GetString("mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string monitoring {
            get {
                return ResourceManager.GetString("monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGQ Monitoring.
        /// </summary>
        public static string monitoring_sgq {
            get {
                return ResourceManager.GetString("monitoring_sgq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Columns.
        /// </summary>
        public static string my_columns {
            get {
                return ResourceManager.GetString("my_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field is required..
        /// </summary>
        public static string name_field_required {
            get {
                return ResourceManager.GetString("name_field_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Action.
        /// </summary>
        public static string new_action {
            get {
                return ResourceManager.GetString("new_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Strategic Planning.
        /// </summary>
        public static string new_strategic_planning {
            get {
                return ResourceManager.GetString("new_strategic_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tactic.
        /// </summary>
        public static string new_tactic {
            get {
                return ResourceManager.GetString("new_tactic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tactical Planning Linked.
        /// </summary>
        public static string new_tactical_planning_linked {
            get {
                return ResourceManager.GetString("new_tactical_planning_linked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tactical Planning Linked to Strategic Planning.
        /// </summary>
        public static string new_tactical_planning_linked_strategic_planning {
            get {
                return ResourceManager.GetString("new_tactical_planning_linked_strategic_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Tasks.
        /// </summary>
        public static string next_tasks {
            get {
                return ResourceManager.GetString("next_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operational planning.
        /// </summary>
        public static string no_operational_planning {
            get {
                return ResourceManager.GetString("no_operational_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string no_records_found {
            get {
                return ResourceManager.GetString("no_records_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specific action.
        /// </summary>
        public static string no_specific_action {
            get {
                return ResourceManager.GetString("no_specific_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string not_started {
            get {
                return ResourceManager.GetString("not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string nov {
            get {
                return ResourceManager.GetString("nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string nov2 {
            get {
                return ResourceManager.GetString("nov2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Action.
        /// </summary>
        public static string number_action {
            get {
                return ResourceManager.GetString("number_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string observation {
            get {
                return ResourceManager.GetString("observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string oct {
            get {
                return ResourceManager.GetString("oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string oct2 {
            get {
                return ResourceManager.GetString("oct2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing Tasks.
        /// </summary>
        public static string ongoing_tasks {
            get {
                return ResourceManager.GetString("ongoing_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Indicator.
        /// </summary>
        public static string operational_indicator {
            get {
                return ResourceManager.GetString("operational_indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Indicators.
        /// </summary>
        public static string operational_indicators {
            get {
                return ResourceManager.GetString("operational_indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Planning.
        /// </summary>
        public static string operational_planning {
            get {
                return ResourceManager.GetString("operational_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Planning Follow-up.
        /// </summary>
        public static string operational_planning_follow_up {
            get {
                return ResourceManager.GetString("operational_planning_follow_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by Value.
        /// </summary>
        public static string order_by_value {
            get {
                return ResourceManager.GetString("order_by_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        public static string password_field_required {
            get {
                return ResourceManager.GetString("password_field_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Completed.
        /// </summary>
        public static string percent_completed {
            get {
                return ResourceManager.GetString("percent_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % COMPLETED - AREA.
        /// </summary>
        public static string percent_completed_area {
            get {
                return ResourceManager.GetString("percent_completed_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % COMPLETED - DEMANDS.
        /// </summary>
        public static string percent_completed_demands {
            get {
                return ResourceManager.GetString("percent_completed_demands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Conclusion.
        /// </summary>
        public static string percent_conclusion {
            get {
                return ResourceManager.GetString("percent_conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERCENTAGE OF NON-CONFORMITY OF TASKS.
        /// </summary>
        public static string percentage_nc_tasks {
            get {
                return ResourceManager.GetString("percentage_nc_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan of Action - Authentication.
        /// </summary>
        public static string plan_action_authentication {
            get {
                return ResourceManager.GetString("plan_action_authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string planning {
            get {
                return ResourceManager.GetString("planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predecessor:.
        /// </summary>
        public static string predecessor {
            get {
                return ResourceManager.GetString("predecessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem or Deviation.
        /// </summary>
        public static string problem_deviation {
            get {
                return ResourceManager.GetString("problem_deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project / Initiative.
        /// </summary>
        public static string project_initiative {
            get {
                return ResourceManager.GetString("project_initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview.
        /// </summary>
        public static string project_overview {
            get {
                return ResourceManager.GetString("project_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview Guideline.
        /// </summary>
        public static string project_overview_guideline {
            get {
                return ResourceManager.GetString("project_overview_guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview Management.
        /// </summary>
        public static string project_overview_management {
            get {
                return ResourceManager.GetString("project_overview_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Theme.
        /// </summary>
        public static string project_theme {
            get {
                return ResourceManager.GetString("project_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string quality {
            get {
                return ResourceManager.GetString("quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of Actions.
        /// </summary>
        public static string quantity_actions {
            get {
                return ResourceManager.GetString("quantity_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECURRENCE OF DEVIATIONS IN THE PERIOD.
        /// </summary>
        public static string recurrence_deviations_period {
            get {
                return ResourceManager.GetString("recurrence_deviations_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional.
        /// </summary>
        public static string regional {
            get {
                return ResourceManager.GetString("regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry successfully saved!.
        /// </summary>
        public static string registry_successfully_saved {
            get {
                return ResourceManager.GetString("registry_successfully_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields.
        /// </summary>
        public static string required_fields {
            get {
                return ResourceManager.GetString("required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible for the Guideline.
        /// </summary>
        public static string responsible_guideline {
            get {
                return ResourceManager.GetString("responsible_guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible for the Project / Initiative.
        /// </summary>
        public static string responsible_project_initiative {
            get {
                return ResourceManager.GetString("responsible_project_initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string sat {
            get {
                return ResourceManager.GetString("sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Columns.
        /// </summary>
        public static string save_columns {
            get {
                return ResourceManager.GetString("save_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edition.
        /// </summary>
        public static string save_edition {
            get {
                return ResourceManager.GetString("save_edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Operational.
        /// </summary>
        public static string save_operational {
            get {
                return ResourceManager.GetString("save_operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Strategic.
        /// </summary>
        public static string save_strategic {
            get {
                return ResourceManager.GetString("save_strategic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tactical.
        /// </summary>
        public static string save_tactical {
            get {
                return ResourceManager.GetString("save_tactical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Planning.
        /// </summary>
        public static string search_planning {
            get {
                return ResourceManager.GetString("search_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string seen {
            get {
                return ResourceManager.GetString("seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a predecessor above.
        /// </summary>
        public static string select_a_predecessor_above {
            get {
                return ResourceManager.GetString("select_a_predecessor_above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a delivery date greater than today&apos;s date!.
        /// </summary>
        public static string select_delivery_date_greater_today_date {
            get {
                return ResourceManager.GetString("select_delivery_date_greater_today_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select....
        /// </summary>
        public static string select2 {
            get {
                return ResourceManager.GetString("select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string selection {
            get {
                return ResourceManager.GetString("selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sept.
        /// </summary>
        public static string sept {
            get {
                return ResourceManager.GetString("sept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string sept2 {
            get {
                return ResourceManager.GetString("sept2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string show_all {
            get {
                return ResourceManager.GetString("show_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 records.
        /// </summary>
        public static string showing_0_to_0_of_0_records {
            get {
                return ResourceManager.GetString("showing_0_to_0_of_0_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ records.
        /// </summary>
        public static string showing_start_to_end_of_total_records {
            get {
                return ResourceManager.GetString("showing_start_to_end_of_total_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature 1.
        /// </summary>
        public static string signature1 {
            get {
                return ResourceManager.GetString("signature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature 2.
        /// </summary>
        public static string signature2 {
            get {
                return ResourceManager.GetString("signature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :  Sort Columns Ascending.
        /// </summary>
        public static string sort_columns_ascending {
            get {
                return ResourceManager.GetString("sort_columns_ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :  Sort columns downward.
        /// </summary>
        public static string sort_columns_downward {
            get {
                return ResourceManager.GetString("sort_columns_downward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Action.
        /// </summary>
        public static string specific_action {
            get {
                return ResourceManager.GetString("specific_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIFIC ACTION.
        /// </summary>
        public static string specific_action2 {
            get {
                return ResourceManager.GetString("specific_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIFIC CAUSE.
        /// </summary>
        public static string specific_cause {
            get {
                return ResourceManager.GetString("specific_cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Cause.
        /// </summary>
        public static string specific_cause2 {
            get {
                return ResourceManager.GetString("specific_cause2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date must be less than End Date!.
        /// </summary>
        public static string start_date_must_be_less_than_end_date {
            get {
                return ResourceManager.GetString("start_date_must_be_less_than_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date Project / Initiative.
        /// </summary>
        public static string start_date_project_initiative {
            get {
                return ResourceManager.GetString("start_date_project_initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks in Action.
        /// </summary>
        public static string stocks_in_action {
            get {
                return ResourceManager.GetString("stocks_in_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategic.
        /// </summary>
        public static string strategic {
            get {
                return ResourceManager.GetString("strategic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategic Planning.
        /// </summary>
        public static string strategic_planning {
            get {
                return ResourceManager.GetString("strategic_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string sun {
            get {
                return ResourceManager.GetString("sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string supervisor {
            get {
                return ResourceManager.GetString("supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Actions.
        /// </summary>
        public static string table_of_actions {
            get {
                return ResourceManager.GetString("table_of_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Projects.
        /// </summary>
        public static string table_of_projects {
            get {
                return ResourceManager.GetString("table_of_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical.
        /// </summary>
        public static string tactical {
            get {
                return ResourceManager.GetString("tactical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Link.
        /// </summary>
        public static string tactical_link {
            get {
                return ResourceManager.GetString("tactical_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Planning.
        /// </summary>
        public static string tactical_planning {
            get {
                return ResourceManager.GetString("tactical_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGQ Task.
        /// </summary>
        public static string task_sgq {
            get {
                return ResourceManager.GetString("task_sgq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Manager.
        /// </summary>
        public static string tasks_manager {
            get {
                return ResourceManager.GetString("tasks_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks vs Status.
        /// </summary>
        public static string tasks_status {
            get {
                return ResourceManager.GetString("tasks_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string term {
            get {
                return ResourceManager.GetString("term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme / Subject.
        /// </summary>
        public static string theme_subject {
            get {
                return ResourceManager.GetString("theme_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thur.
        /// </summary>
        public static string thur {
            get {
                return ResourceManager.GetString("thur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Manage:.
        /// </summary>
        public static string to_manage {
            get {
                return ResourceManager.GetString("to_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string tue {
            get {
                return ResourceManager.GetString("tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Project.
        /// </summary>
        public static string type_of_project {
            get {
                return ResourceManager.GetString("type_of_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the password.
        /// </summary>
        public static string type_password {
            get {
                return ResourceManager.GetString("type_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the user.
        /// </summary>
        public static string type_user {
            get {
                return ResourceManager.GetString("type_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement.
        /// </summary>
        public static string unit_measurement {
            get {
                return ResourceManager.GetString("unit_measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        public static string until {
            get {
                return ResourceManager.GetString("until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated link!.
        /// </summary>
        public static string updated_link {
            get {
                return ResourceManager.GetString("updated_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is invalid..
        /// </summary>
        public static string username_password_invalid {
            get {
                return ResourceManager.GetString("username_password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for.
        /// </summary>
        public static string value_for {
            get {
                return ResourceManager.GetString("value_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of.
        /// </summary>
        public static string value_of {
            get {
                return ResourceManager.GetString("value_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Columns.
        /// </summary>
        public static string visible_columns {
            get {
                return ResourceManager.GetString("visible_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string wed {
            get {
                return ResourceManager.GetString("wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When (End).
        /// </summary>
        public static string when_end {
            get {
                return ResourceManager.GetString("when_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When End.
        /// </summary>
        public static string when_end2 {
            get {
                return ResourceManager.GetString("when_end2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When (Start).
        /// </summary>
        public static string when_start {
            get {
                return ResourceManager.GetString("when_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Start.
        /// </summary>
        public static string when_start2 {
            get {
                return ResourceManager.GetString("when_start2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who.
        /// </summary>
        public static string who {
            get {
                return ResourceManager.GetString("who", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Status.
        /// </summary>
        public static string without_status {
            get {
                return ResourceManager.GetString("without_status", resourceCulture);
            }
        }
    }
}
