//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active:.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string active2 {
            get {
                return ResourceManager.GetString("active2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        internal static string active3 {
            get {
                return ResourceManager.GetString("active3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action.
        /// </summary>
        internal static string add_action {
            get {
                return ResourceManager.GetString("add_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string all2 {
            get {
                return ResourceManager.GetString("all2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Plannings to Filter.
        /// </summary>
        internal static string all_plannings_to_filter {
            get {
                return ResourceManager.GetString("all_plannings_to_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks to filter.
        /// </summary>
        internal static string all_tasks_to_filter {
            get {
                return ResourceManager.GetString("all_tasks_to_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        internal static string apr {
            get {
                return ResourceManager.GetString("apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        internal static string aug {
            get {
                return ResourceManager.GetString("aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY STATUS.
        /// </summary>
        internal static string by_status {
            get {
                return ResourceManager.GetString("by_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change planning.
        /// </summary>
        internal static string change_planning {
            get {
                return ResourceManager.GetString("change_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Strategic Link.
        /// </summary>
        internal static string change_strategic_link {
            get {
                return ResourceManager.GetString("change_strategic_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tactical Link.
        /// </summary>
        internal static string change_tactical_link {
            get {
                return ResourceManager.GetString("change_tactical_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative.
        /// </summary>
        internal static string comparative {
            get {
                return ResourceManager.GetString("comparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Tasks.
        /// </summary>
        internal static string completed_tasks {
            get {
                return ResourceManager.GetString("completed_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordination.
        /// </summary>
        internal static string coordination {
            get {
                return ResourceManager.GetString("coordination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save record:.
        /// </summary>
        internal static string could_not_save_record {
            get {
                return ResourceManager.GetString("could_not_save_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the conclusion.
        /// </summary>
        internal static string date_conclusion {
            get {
                return ResourceManager.GetString("date_conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of delay.
        /// </summary>
        internal static string days_of_delay {
            get {
                return ResourceManager.GetString("days_of_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        internal static string dec {
            get {
                return ResourceManager.GetString("dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed Tasks.
        /// </summary>
        internal static string delayed_tasks {
            get {
                return ResourceManager.GetString("delayed_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        internal static string dimension {
            get {
                return ResourceManager.GetString("dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorship.
        /// </summary>
        internal static string directorship {
            get {
                return ResourceManager.GetString("directorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Action.
        /// </summary>
        internal static string edit_action {
            get {
                return ResourceManager.GetString("edit_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        internal static string feb {
            get {
                return ResourceManager.GetString("feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields must be completed.
        /// </summary>
        internal static string fields_must_be_completed {
            get {
                return ResourceManager.GetString("fields_must_be_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Filtered _MAX_ records).
        /// </summary>
        internal static string filtered_max_records {
            get {
                return ResourceManager.GetString("filtered_max_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMATION OF STOCKS IN ACTION.
        /// </summary>
        internal static string formation_of_stocks_in_action {
            get {
                return ResourceManager.GetString("formation_of_stocks_in_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form of.
        /// </summary>
        internal static string form_of {
            get {
                return ResourceManager.GetString("form_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Action.
        /// </summary>
        internal static string generic_action {
            get {
                return ResourceManager.GetString("generic_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Cause.
        /// </summary>
        internal static string generic_cause {
            get {
                return ResourceManager.GetString("generic_cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Cause.
        /// </summary>
        internal static string group_cause {
            get {
                return ResourceManager.GetString("group_cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guideline.
        /// </summary>
        internal static string guideline {
            get {
                return ResourceManager.GetString("guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INACTIVE.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator.
        /// </summary>
        internal static string indicator {
            get {
                return ResourceManager.GetString("indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators / Guideline.
        /// </summary>
        internal static string indicators_guideline {
            get {
                return ResourceManager.GetString("indicators_guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Type.
        /// </summary>
        internal static string indicator_type {
            get {
                return ResourceManager.GetString("indicator_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name:.
        /// </summary>
        internal static string item_name {
            get {
                return ResourceManager.GetString("item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        internal static string jan {
            get {
                return ResourceManager.GetString("jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        internal static string mar {
            get {
                return ResourceManager.GetString("mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MENU_ results per page.
        /// </summary>
        internal static string menu_results_per_page {
            get {
                return ResourceManager.GetString("menu_results_per_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        internal static string monitoring {
            get {
                return ResourceManager.GetString("monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Action.
        /// </summary>
        internal static string new_action {
            get {
                return ResourceManager.GetString("new_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Strategic Planning.
        /// </summary>
        internal static string new_strategic_planning {
            get {
                return ResourceManager.GetString("new_strategic_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tactic.
        /// </summary>
        internal static string new_tactic {
            get {
                return ResourceManager.GetString("new_tactic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tactical Planning Linked to Strategic Planning.
        /// </summary>
        internal static string new_tactical_planning_linked_strategic_planning {
            get {
                return ResourceManager.GetString("new_tactical_planning_linked_strategic_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Tasks.
        /// </summary>
        internal static string next_tasks {
            get {
                return ResourceManager.GetString("next_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string nov {
            get {
                return ResourceManager.GetString("nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string no_records_found {
            get {
                return ResourceManager.GetString("no_records_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specific action.
        /// </summary>
        internal static string no_specific_action {
            get {
                return ResourceManager.GetString("no_specific_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        internal static string oct {
            get {
                return ResourceManager.GetString("oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing Tasks.
        /// </summary>
        internal static string ongoing_tasks {
            get {
                return ResourceManager.GetString("ongoing_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Planning.
        /// </summary>
        internal static string operational_planning {
            get {
                return ResourceManager.GetString("operational_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Planning Follow-up.
        /// </summary>
        internal static string operational_planning_follow_up {
            get {
                return ResourceManager.GetString("operational_planning_follow_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Completed.
        /// </summary>
        internal static string percent_completed {
            get {
                return ResourceManager.GetString("percent_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % COMPLETED - AREA.
        /// </summary>
        internal static string percent_completed_area {
            get {
                return ResourceManager.GetString("percent_completed_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % COMPLETED - DEMANDS.
        /// </summary>
        internal static string percent_completed_demands {
            get {
                return ResourceManager.GetString("percent_completed_demands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Conclusion.
        /// </summary>
        internal static string percent_conclusion {
            get {
                return ResourceManager.GetString("percent_conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        internal static string planning {
            get {
                return ResourceManager.GetString("planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predecessor:.
        /// </summary>
        internal static string predecessor {
            get {
                return ResourceManager.GetString("predecessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project / Initiative.
        /// </summary>
        internal static string project_initiative {
            get {
                return ResourceManager.GetString("project_initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview.
        /// </summary>
        internal static string project_overview {
            get {
                return ResourceManager.GetString("project_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview Guideline.
        /// </summary>
        internal static string project_overview_guideline {
            get {
                return ResourceManager.GetString("project_overview_guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview Management.
        /// </summary>
        internal static string project_overview_management {
            get {
                return ResourceManager.GetString("project_overview_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Theme.
        /// </summary>
        internal static string project_theme {
            get {
                return ResourceManager.GetString("project_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional.
        /// </summary>
        internal static string regional {
            get {
                return ResourceManager.GetString("regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry successfully saved!.
        /// </summary>
        internal static string registry_successfully_saved {
            get {
                return ResourceManager.GetString("registry_successfully_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields.
        /// </summary>
        internal static string required_fields {
            get {
                return ResourceManager.GetString("required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edition.
        /// </summary>
        internal static string save_edition {
            get {
                return ResourceManager.GetString("save_edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Operational.
        /// </summary>
        internal static string save_operational {
            get {
                return ResourceManager.GetString("save_operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Strategic.
        /// </summary>
        internal static string save_strategic {
            get {
                return ResourceManager.GetString("save_strategic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tactical.
        /// </summary>
        internal static string save_tactical {
            get {
                return ResourceManager.GetString("save_tactical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Planning.
        /// </summary>
        internal static string search_planning {
            get {
                return ResourceManager.GetString("search_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a predecessor above.
        /// </summary>
        internal static string select_a_predecessor_above {
            get {
                return ResourceManager.GetString("select_a_predecessor_above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sept.
        /// </summary>
        internal static string sept {
            get {
                return ResourceManager.GetString("sept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 records.
        /// </summary>
        internal static string showing_0_to_0_of_0_records {
            get {
                return ResourceManager.GetString("showing_0_to_0_of_0_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ records.
        /// </summary>
        internal static string showing_start_to_end_of_total_records {
            get {
                return ResourceManager.GetString("showing_start_to_end_of_total_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :  Sort Columns Ascending.
        /// </summary>
        internal static string sort_columns_ascending {
            get {
                return ResourceManager.GetString("sort_columns_ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :  Sort columns downward.
        /// </summary>
        internal static string sort_columns_downward {
            get {
                return ResourceManager.GetString("sort_columns_downward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Action.
        /// </summary>
        internal static string specific_action {
            get {
                return ResourceManager.GetString("specific_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date must be less than End Date!.
        /// </summary>
        internal static string start_date_must_be_less_than_end_date {
            get {
                return ResourceManager.GetString("start_date_must_be_less_than_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks in Action.
        /// </summary>
        internal static string stocks_in_action {
            get {
                return ResourceManager.GetString("stocks_in_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Actions.
        /// </summary>
        internal static string table_of_actions {
            get {
                return ResourceManager.GetString("table_of_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Projects.
        /// </summary>
        internal static string table_of_projects {
            get {
                return ResourceManager.GetString("table_of_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Planning.
        /// </summary>
        internal static string tactical_planning {
            get {
                return ResourceManager.GetString("tactical_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Manager.
        /// </summary>
        internal static string tasks_manager {
            get {
                return ResourceManager.GetString("tasks_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks vs Status.
        /// </summary>
        internal static string tasks_status {
            get {
                return ResourceManager.GetString("tasks_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme / Subject.
        /// </summary>
        internal static string theme_subject {
            get {
                return ResourceManager.GetString("theme_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Manage:.
        /// </summary>
        internal static string to_manage {
            get {
                return ResourceManager.GetString("to_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Project.
        /// </summary>
        internal static string type_of_project {
            get {
                return ResourceManager.GetString("type_of_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated link!.
        /// </summary>
        internal static string updated_link {
            get {
                return ResourceManager.GetString("updated_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who.
        /// </summary>
        internal static string who {
            get {
                return ResourceManager.GetString("who", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("_new", resourceCulture);
            }
        }
    }
}
