//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert emissor.
        /// </summary>
        internal static string alert_emissor {
            get {
                return ResourceManager.GetString("alert_emissor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow create and/or edit of tasks.
        /// </summary>
        internal static string allow_create_and_or_edit_of_tasks {
            get {
                return ResourceManager.GetString("allow_create_and_or_edit_of_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow field edition of the header.
        /// </summary>
        internal static string allow_field_edition_of_the_header {
            get {
                return ResourceManager.GetString("allow_field_edition_of_the_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow specific register by unit.
        /// </summary>
        internal static string allow_specific_register_by_unit {
            get {
                return ResourceManager.GetString("allow_specific_register_by_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the edition of the evaluation number.
        /// </summary>
        internal static string allow_the_edition_of_the_evaluation_number {
            get {
                return ResourceManager.GetString("allow_the_edition_of_the_evaluation_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the edition of the goal of the indicator by unit.
        /// </summary>
        internal static string allow_the_edition_of_the_goal_of_the_indicator_by_unit {
            get {
                return ResourceManager.GetString("allow_the_edition_of_the_goal_of_the_indicator_by_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the edition of the sample number.
        /// </summary>
        internal static string allow_the_edition_of_the_sample_number {
            get {
                return ResourceManager.GetString("allow_the_edition_of_the_sample_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the not applicable button (NA) on level2.
        /// </summary>
        internal static string allow_the_not_applicable_button_on_level2 {
            get {
                return ResourceManager.GetString("allow_the_not_applicable_button_on_level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor.
        /// </summary>
        internal static string auditor {
            get {
                return ResourceManager.GetString("auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string authenticating {
            get {
                return ResourceManager.GetString("authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidation Type.
        /// </summary>
        internal static string consolidation_type {
            get {
                return ResourceManager.GetString("consolidation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the type of consolidation between patterns types. System counters will be based on the kind of consolidation..
        /// </summary>
        internal static string consolidation_type_popover {
            get {
                return ResourceManager.GetString("consolidation_type_popover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Action Reports.
        /// </summary>
        internal static string corrective_action_reports {
            get {
                return ResourceManager.GetString("corrective_action_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection Reports.
        /// </summary>
        internal static string data_collection_reports {
            get {
                return ResourceManager.GetString("data_collection_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emit warning.
        /// </summary>
        internal static string emit_warning {
            get {
                return ResourceManager.GetString("emit_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated.
        /// </summary>
        internal static string evaluated {
            get {
                return ResourceManager.GetString("evaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field level.
        /// </summary>
        internal static string field_level {
            get {
                return ResourceManager.GetString("field_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define on which header (Level 1 or Level 2) the field will be inserted.
        /// </summary>
        internal static string field_level_popover {
            get {
                return ResourceManager.GetString("field_level_popover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal value  (%).
        /// </summary>
        internal static string goal_value {
            get {
                return ResourceManager.GetString("goal_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header fields.
        /// </summary>
        internal static string header_fields {
            get {
                return ResourceManager.GetString("header_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Description.
        /// </summary>
        internal static string indicator_description {
            get {
                return ResourceManager.GetString("indicator_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Name.
        /// </summary>
        internal static string indicator_name {
            get {
                return ResourceManager.GetString("indicator_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JBS and GRT Application.
        /// </summary>
        internal static string jbs_and_grt_aplication {
            get {
                return ResourceManager.GetString("jbs_and_grt_aplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 Clusters.
        /// </summary>
        internal static string level1_clusters {
            get {
                return ResourceManager.GetString("level1_clusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 counter.
        /// </summary>
        internal static string level1_counter {
            get {
                return ResourceManager.GetString("level1_counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2 group.
        /// </summary>
        internal static string level2_group {
            get {
                return ResourceManager.GetString("level2_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Avaliações Limitado.
        /// </summary>
        internal static string limited_number_of_evaluations {
            get {
                return ResourceManager.GetString("limited_number_of_evaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string log_in {
            get {
                return ResourceManager.GetString("log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string log_out {
            get {
                return ResourceManager.GetString("log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not conformity rule.
        /// </summary>
        internal static string not_conformity_rule {
            get {
                return ResourceManager.GetString("not_conformity_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        internal static string please_sign_in {
            get {
                return ResourceManager.GetString("please_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaudit.
        /// </summary>
        internal static string reaudit {
            get {
                return ResourceManager.GetString("reaudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Total Evaluated.
        /// </summary>
        internal static string register_total_evaluated {
            get {
                return ResourceManager.GetString("register_total_evaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string rule {
            get {
                return ResourceManager.GetString("rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save button on level2.
        /// </summary>
        internal static string save_button_on_level2 {
            get {
                return ResourceManager.GetString("save_button_on_level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the consolidation type.
        /// </summary>
        internal static string select_the_consolidation_type {
            get {
                return ResourceManager.GetString("select_the_consolidation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show level 1 counters.
        /// </summary>
        internal static string show_level1_counters {
            get {
                return ResourceManager.GetString("show_level1_counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
    }
}
