//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgqSystem.PlanoAcao.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcompanhamentoTarefa> AcompanhamentoTarefa { get; set; }
        public virtual DbSet<Campo> Cabecalho { get; set; }
        public virtual DbSet<Campo> Campo { get; set; }
        public virtual DbSet<ConfiguracaoEmailPA> ConfiguracaoEmailPA { get; set; }
        public virtual DbSet<GrupoCabecalho> GrupoCabecalho { get; set; }
        public virtual DbSet<GrupoProjeto> GrupoProjeto { get; set; }
        public virtual DbSet<LogOperacaoPA> LogOperacaoPA { get; set; }
        public virtual DbSet<MultiplaEscolha> MultiplaEscolha { get; set; }
        public virtual DbSet<Projeto> Projeto { get; set; }
        public virtual DbSet<TarefaPA> TarefaPA { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<VinculoCampoCabecalho> VinculoCampoCabecalho { get; set; }
        public virtual DbSet<VinculoCampoTarefa> VinculoCampoTarefa { get; set; }
        public virtual DbSet<VinculoParticipanteMultiplaEscolha> VinculoParticipanteMultiplaEscolha { get; set; }
        public virtual DbSet<VinculoParticipanteProjeto> VinculoParticipanteProjeto { get; set; }
        public virtual DbSet<VIEW_STATUS_PA> VIEW_STATUS_PA { get; set; }
    }
}
