//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgqSystem.PlanoAcao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.AcompanhamentoTarefa = new HashSet<AcompanhamentoTarefa>();
            this.Cabecalho = new HashSet<Campo>();
            this.TarefaPA = new HashSet<TarefaPA>();
            this.VinculoCampoCabecalho = new HashSet<VinculoCampoCabecalho>();
            this.VinculoCampoTarefa = new HashSet<VinculoCampoTarefa>();
            this.VinculoParticipanteMultiplaEscolha = new HashSet<VinculoParticipanteMultiplaEscolha>();
            this.VinculoParticipanteProjeto = new HashSet<VinculoParticipanteProjeto>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Identificador { get; set; }
        public int Unidade { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string Nome { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string Funcao { get; set; }
        public string Email { get; set; }
        public Nullable<bool> DefineFamilia { get; set; }
        public Nullable<bool> DefineParametros { get; set; }
        public Nullable<bool> EditaUsuarios { get; set; }
        public Nullable<bool> ReceberAlerta { get; set; }
        public Nullable<int> Regional { get; set; }
        public System.DateTime DataAlteracaoSenha { get; set; }
        public Nullable<bool> ConfiguraSistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcompanhamentoTarefa> AcompanhamentoTarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campo> Cabecalho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaPA> TarefaPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinculoCampoCabecalho> VinculoCampoCabecalho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinculoCampoTarefa> VinculoCampoTarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinculoParticipanteMultiplaEscolha> VinculoParticipanteMultiplaEscolha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinculoParticipanteProjeto> VinculoParticipanteProjeto { get; set; }
    }
}
