//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgqSystem.PlanoAcao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_STATUS_PA
    {
        public int Id { get; set; }
        public Nullable<int> IdMultiplaEscolha { get; set; }
        public int IdCampo { get; set; }
        public int IdTarefa { get; set; }
        public string Valor { get; set; }
        public Nullable<int> IdParticipante { get; set; }
    }
}
