//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcoesPreventivas
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public int Departamento { get; set; }
        public int Operacao { get; set; }
        public int Tarefa { get; set; }
        public int Avaliacao { get; set; }
        public int Amostra { get; set; }
        public string Motivo { get; set; }
        public string AcaoPreventiva { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    }
}
