//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcompanhamentoTarefa
    {
        public int Id { get; set; }
        public int IdTarefa { get; set; }
        public System.DateTime DataEnvio { get; set; }
        public string Comentario { get; set; }
        public string Enviado { get; set; }
        public string Status { get; set; }
        public string NomeParticipanteEnvio { get; set; }
        public int IdParticipanteEnvio { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual TarefaPA TarefaPA { get; set; }
    }
}
