//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas
    {
        public int Id { get; set; }
        public Nullable<int> Unidade { get; set; }
        public Nullable<int> Operacao { get; set; }
        public Nullable<int> Tarefa { get; set; }
        public string Mensagem { get; set; }
        public Nullable<int> Incidencia { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        public virtual Operacoes Operacoes { get; set; }
        public virtual Tarefas Tarefas { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
