//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class budgets
    {
        public byte dept { get; set; }
        public Nullable<decimal> current_year { get; set; }
        public Nullable<decimal> previous_year { get; set; }
    }
}
