//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracteristicaTipificacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaracteristicaTipificacao()
        {
            this.CaracteristicaTipificacaoSequencial = new HashSet<CaracteristicaTipificacaoSequencial>();
        }
    
        public decimal nCdCaracteristica { get; set; }
        public string cNmCaracteristica { get; set; }
        public string cNrCaracteristica { get; set; }
        public string cSgCaracteristica { get; set; }
        public string cIdentificador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristicaTipificacaoSequencial> CaracteristicaTipificacaoSequencial { get; set; }
    }
}
