//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionLevel2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectionLevel2()
        {
            this.CollectionLevel2XParHeaderField = new HashSet<CollectionLevel2XParHeaderField>();
            this.Result_Level3 = new HashSet<Result_Level3>();
        }
    
        public int Id { get; set; }
        public int ConsolidationLevel2_Id { get; set; }
        public int ParLevel1_Id { get; set; }
        public int ParLevel2_Id { get; set; }
        public int UnitId { get; set; }
        public int AuditorId { get; set; }
        public int Shift { get; set; }
        public int Period { get; set; }
        public int Phase { get; set; }
        public bool ReauditIs { get; set; }
        public int ReauditNumber { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public System.DateTime StartPhaseDate { get; set; }
        public Nullable<int> EvaluationNumber { get; set; }
        public int Sample { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool ConsecutiveFailureIs { get; set; }
        public int ConsecutiveFailureTotal { get; set; }
        public bool NotEvaluatedIs { get; set; }
        public bool Duplicated { get; set; }
        public Nullable<bool> HaveCorrectiveAction { get; set; }
        public Nullable<bool> HaveReaudit { get; set; }
        public Nullable<bool> HavePhase { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> ParFrequency_Id { get; set; }
        public Nullable<int> AlertLevel { get; set; }
        public Nullable<int> Sequential { get; set; }
        public Nullable<int> Side { get; set; }
        public Nullable<decimal> WeiEvaluation { get; set; }
        public Nullable<decimal> Defects { get; set; }
        public Nullable<decimal> WeiDefects { get; set; }
        public Nullable<int> TotalLevel3WithDefects { get; set; }
        public Nullable<int> TotalLevel3Evaluation { get; set; }
        public Nullable<int> LastEvaluationAlert { get; set; }
        public Nullable<int> EvaluatedResult { get; set; }
        public Nullable<int> DefectsResult { get; set; }
    
        public virtual ConsolidationLevel2 ConsolidationLevel2 { get; set; }
        public virtual ParLevel1 ParLevel1 { get; set; }
        public virtual ParLevel2 ParLevel2 { get; set; }
        public virtual UserSgq UserSgq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionLevel2XParHeaderField> CollectionLevel2XParHeaderField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result_Level3> Result_Level3 { get; set; }
    }
}
