//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionLevel02
    {
        public int Id { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public int ConsolidationLevel02_Id { get; set; }
        public int Auditor_Id { get; set; }
        public int CattleType_Id { get; set; }
        public int Level01_Id { get; set; }
        public int Level02_Id { get; set; }
        public int Unit_Id { get; set; }
        public decimal Chainspeed { get; set; }
        public bool ConsecutiveFailureIs { get; set; }
        public int ConsecutiveFailureTotal { get; set; }
        public decimal LotNumber { get; set; }
        public decimal Mudscore { get; set; }
        public int Period { get; set; }
        public int Phase { get; set; }
        public bool ReauditIs { get; set; }
        public int ReauditNumber { get; set; }
        public bool NotEvaluatedIs { get; set; }
        public int Sample { get; set; }
        public int Shift { get; set; }
        public System.DateTime StartPhaseDate { get; set; }
    }
}
