//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionLevel03
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectionLevel03()
        {
            this.CorrectiveAction = new HashSet<CorrectiveAction>();
        }
    
        public int Id { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public int CollectionLevel02Id { get; set; }
        public Nullable<int> Level03Id { get; set; }
        public bool ConformedIs { get; set; }
        public decimal Value { get; set; }
        public string ValueText { get; set; }
    
        public virtual CollectionLevel02 CollectionLevel02 { get; set; }
        public virtual Level03 Level03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrectiveAction> CorrectiveAction { get; set; }
    }
}
