//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionLevel2XParHeaderField
    {
        public int Id { get; set; }
        public int CollectionLevel2_Id { get; set; }
        public int ParHeaderField_Id { get; set; }
        public string ParHeaderField_Name { get; set; }
        public int ParFieldType_Id { get; set; }
        public string Value { get; set; }
    
        public virtual CollectionLevel2 CollectionLevel2 { get; set; }
        public virtual ParFieldType ParFieldType { get; set; }
        public virtual ParHeaderField ParHeaderField { get; set; }
    }
}
