//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsolidationLevel02
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsolidationLevel02()
        {
            this.CollectionLevel02 = new HashSet<CollectionLevel02>();
        }
    
        public int Id { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public Nullable<System.DateTime> ConsolidationDate { get; set; }
        public int Level01ConsolidationId { get; set; }
        public int Level02Id { get; set; }
    
        public virtual ConsolidationLevel01 ConsolidationLevel01 { get; set; }
        public virtual Level02 Level02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionLevel02> CollectionLevel02 { get; set; }
    }
}
