//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContramedidaGenerica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContramedidaGenerica()
        {
            this.fa_ContramedidaGenerica = new HashSet<fa_ContramedidaGenerica>();
        }
    
        public int Id { get; set; }
        public string ContramedidaGenerica1 { get; set; }
        public Nullable<int> CausaGenerica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_ContramedidaGenerica> fa_ContramedidaGenerica { get; set; }
    }
}
