//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrectiveActionLevels
    {
        public int Id { get; set; }
        public int CorrectiveActionId { get; set; }
        public int AuditLevel01Id { get; set; }
        public int AuditLevel02Id { get; set; }
        public int AuditLevel03Id { get; set; }
        public Nullable<int> Defects { get; set; }
    
        public virtual CorrectiveAction CorrectiveAction { get; set; }
    }
}
