//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrectiveAction
    {
        public int Id { get; set; }
        public System.DateTime DateExecute { get; set; }
        public int Auditor { get; set; }
        public int Shift { get; set; }
        public int AuditLevel1 { get; set; }
        public int AuditLevel2 { get; set; }
        public int AuditLevel3 { get; set; }
        public System.DateTime StartTime { get; set; }
        public int Period { get; set; }
        public string DescriptionFailure { get; set; }
        public string ImmediateCorrectiveAction { get; set; }
        public string ProductDisposition { get; set; }
        public string PreventativeMeasure { get; set; }
        public Nullable<int> Slaughter { get; set; }
        public Nullable<System.DateTime> DateTimeSlaughter { get; set; }
        public Nullable<int> Techinical { get; set; }
        public Nullable<System.DateTime> DateTimeTechinical { get; set; }
        public string NameTechinical { get; set; }
        public string NameSlaughter { get; set; }
    }
}
