//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrectiveAction
    {
        public int Id { get; set; }
        public int AuditorId { get; set; }
        public int CollectionLevel02Id { get; set; }
        public Nullable<int> SlaughterId { get; set; }
        public Nullable<int> TechinicalId { get; set; }
        public Nullable<System.DateTime> DateTimeSlaughter { get; set; }
        public Nullable<System.DateTime> DateTimeTechinical { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public System.DateTime DateCorrectiveAction { get; set; }
        public System.DateTime AuditStartTime { get; set; }
        public string DescriptionFailure { get; set; }
        public string ImmediateCorrectiveAction { get; set; }
        public string ProductDisposition { get; set; }
        public string PreventativeMeasure { get; set; }
    
        public virtual CollectionLevel02 CollectionLevel02 { get; set; }
        public virtual UserSgq UserSgq { get; set; }
        public virtual UserSgq UserSgq1 { get; set; }
        public virtual UserSgq UserSgq2 { get; set; }
    }
}
