//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataCollection()
        {
            this.DataCollectionResult = new HashSet<DataCollectionResult>();
        }
    
        public int Id { get; set; }
        public int Level02ConsolidationId { get; set; }
        public int EvaluationNumber { get; set; }
        public int SampleNumber { get; set; }
        public int MonitorId { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public System.DateTime AddData { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Access { get; set; }
        public Nullable<int> Sets { get; set; }
        public Nullable<int> Side { get; set; }
        public bool Shared { get; set; }
        public int Plataform { get; set; }
        public bool Processed { get; set; }
    
        public virtual Level02Consolidation Level02Consolidation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataCollectionResult> DataCollectionResult { get; set; }
    }
}
