//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public int deptid { get; set; }
        public string deptname { get; set; }
        public Nullable<int> deptmgrid { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
