//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deviation
    {
        public int Id { get; set; }
        public int ParCompany_Id { get; set; }
        public int ParLevel1_Id { get; set; }
        public int ParLevel2_Id { get; set; }
        public decimal Evaluation { get; set; }
        public decimal Sample { get; set; }
        public int AlertNumber { get; set; }
        public decimal Defects { get; set; }
        public System.DateTime DeviationDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<bool> sendMail { get; set; }
        public string DeviationMessage { get; set; }
        public string Status { get; set; }
        public string SendDate { get; set; }
        public Nullable<int> EmailContent_Id { get; set; }
    
        public virtual EmailContent EmailContent { get; set; }
    }
}
