//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimManutencaoColetaITs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimManutencaoColetaITs()
        {
            this.ManDataCollectIT = new HashSet<ManDataCollectIT>();
        }
    
        public int id { get; set; }
        public string DataType { get; set; }
        public string TechnicalIndicator { get; set; }
        public Nullable<int> ParFrequency_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManDataCollectIT> ManDataCollectIT { get; set; }
    }
}
