//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public decimal nCdEmpresa { get; set; }
        public string cNmEmpresa { get; set; }
        public string cSgEmpresa { get; set; }
        public string cCdOrgaoRegulador { get; set; }
    }
}
