//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_ContramedidaGenerica
    {
        public int Id { get; set; }
        public int IdFormularioTratamentoAnomalia { get; set; }
        public int IdContramedidaGenerica { get; set; }
        public int Prioridade { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual ContramedidaGenerica ContramedidaGenerica { get; set; }
    }
}
