//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioTratamentoAnomalia
    {
        public int Id { get; set; }
        public int Unidade { get; set; }
        public int Operacao { get; set; }
        public int Monitoramento { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public int Tarefa { get; set; }
        public byte[] Versao { get; set; }
        public int Supervisor { get; set; }
        public int Gerente { get; set; }
    }
}
