//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoTipoAvaliacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoTipoAvaliacoes()
        {
            this.GrupoTipoAvaliacaoMonitoramentos = new HashSet<GrupoTipoAvaliacaoMonitoramentos>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Positivo { get; set; }
        public int Negativo { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoTipoAvaliacaoMonitoramentos> GrupoTipoAvaliacaoMonitoramentos { get; set; }
        public virtual TipoAvaliacoes TipoAvaliacoes { get; set; }
        public virtual TipoAvaliacoes TipoAvaliacoes1 { get; set; }
    }
}
