//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level03Consolidation
    {
        public int Id { get; set; }
        public int Level02ConsolidationId { get; set; }
        public int Level03Id { get; set; }
        public System.DateTime DateConsolidation { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public decimal TotalLevel03 { get; set; }
        public decimal TotalLevel03Weight { get; set; }
        public decimal TotalEvaluated { get; set; }
        public decimal totalEvaluatedWeight { get; set; }
        public decimal TotalEvaluatedShared { get; set; }
        public decimal TotalEvaluatedSharedWeight { get; set; }
        public decimal TotalNotConform { get; set; }
        public decimal TotalNotConformWeight { get; set; }
        public decimal TotalNotConformShared { get; set; }
        public decimal TotalNotConformSharedWeight { get; set; }
        public bool Shared { get; set; }
    
        public virtual Level02Consolidation Level02Consolidation { get; set; }
        public virtual Level03 Level03 { get; set; }
    }
}
