//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level01Consolidation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Level01Consolidation()
        {
            this.Level02Consolidation = new HashSet<Level02Consolidation>();
        }
    
        public int Id { get; set; }
        public int CenterResultId { get; set; }
        public int Level01Id { get; set; }
        public System.DateTime DateConsolidation { get; set; }
        public System.DateTime AddDate { get; set; }
        public int TotalLevel02 { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public decimal TotalLevel02Weight { get; set; }
        public decimal TotalEvaluated { get; set; }
        public decimal TotalEvaluatedWeight { get; set; }
        public decimal TotalEvaluatedShared { get; set; }
        public decimal TotalEvaluatedSharedWeight { get; set; }
        public decimal TotalNotConform { get; set; }
        public decimal TotalNotConformWeight { get; set; }
        public decimal TotalNotConformShared { get; set; }
        public decimal TotalNotConformShared_Weight { get; set; }
        public bool Shared { get; set; }
    
        public virtual Level01 Level01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Level02Consolidation> Level02Consolidation { get; set; }
    }
}
