//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogJson
    {
        public int Id { get; set; }
        public string result { get; set; }
        public string log { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Device_Id { get; set; }
        public string AppVersion { get; set; }
        public string callback { get; set; }
    }
}
