//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManBudgetedIndicators
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateRef { get; set; }
        public Nullable<int> ParCompany_id { get; set; }
        public Nullable<int> DimManCMDColetaDados_id { get; set; }
        public Nullable<decimal> ValueBudgetedIndicators { get; set; }
    }
}
