//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManDataCollectIT
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> InstantDatetime { get; set; }
        public Nullable<System.DateTime> ReferenceDatetime { get; set; }
        public Nullable<int> UserSGQ_Id { get; set; }
        public Nullable<int> ParCompany_Id { get; set; }
        public Nullable<int> ParFrequency_Id { get; set; }
        public Nullable<int> Shift { get; set; }
        public string DataType { get; set; }
        public Nullable<decimal> AmountData { get; set; }
        public Nullable<int> ParMeasurementUnit_Id { get; set; }
        public string Comments { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool IsActive { get; set; }
    }
}
