//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operacoes()
        {
            this.AcoesCorretivas = new HashSet<AcoesCorretivas>();
            this.Alertas = new HashSet<Alertas>();
            this.DepartamentoOperacoes = new HashSet<DepartamentoOperacoes>();
            this.FamiliaProdutos = new HashSet<FamiliaProdutos>();
            this.Horarios = new HashSet<Horarios>();
            this.Metas = new HashSet<Metas>();
            this.MonitoramentosConcorrentes = new HashSet<MonitoramentosConcorrentes>();
            this.ObservacoesPadroes = new HashSet<ObservacoesPadroes>();
            this.PacotesOperacoes = new HashSet<PacotesOperacoes>();
            this.Pontos = new HashSet<Pontos>();
            this.TarefaAvaliacoes = new HashSet<TarefaAvaliacoes>();
            this.Tarefas = new HashSet<Tarefas>();
            this.TipificacaoReal = new HashSet<TipificacaoReal>();
            this.VolumeProducao = new HashSet<VolumeProducao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string Nivel { get; set; }
        public string Frequencia { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public Nullable<bool> ControleVP { get; set; }
        public Nullable<bool> ADCAMPOVAZIO { get; set; }
        public Nullable<bool> AvaliarEquipamentos { get; set; }
        public Nullable<bool> AvaliarCamaras { get; set; }
        public Nullable<bool> Especifico { get; set; }
        public Nullable<bool> ExibirPColeta { get; set; }
        public Nullable<bool> PadraoPerc { get; set; }
        public Nullable<bool> ControleFP { get; set; }
        public Nullable<bool> AvaliarSequencial { get; set; }
        public string Criterio { get; set; }
        public string FrequenciaAlerta { get; set; }
        public Nullable<bool> ExibirData { get; set; }
        public Nullable<bool> EmitirAlerta { get; set; }
        public Nullable<bool> ControlarAvaliacoes { get; set; }
        public Nullable<bool> AlterarAmostra { get; set; }
        public Nullable<bool> IncluirTarefa { get; set; }
        public Nullable<bool> IncluirAvaliacao { get; set; }
        public Nullable<bool> AlertaAgruparAvaliacoes { get; set; }
        public Nullable<int> QteFamiliaUnidade { get; set; }
        public Nullable<int> QteFamiliaCorporativa { get; set; }
        public Nullable<bool> ExibirTarefasAcumuladas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcoesCorretivas> AcoesCorretivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alertas> Alertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartamentoOperacoes> DepartamentoOperacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamiliaProdutos> FamiliaProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Metas> Metas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoramentosConcorrentes> MonitoramentosConcorrentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacoesPadroes> ObservacoesPadroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacotesOperacoes> PacotesOperacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pontos> Pontos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaAvaliacoes> TarefaAvaliacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarefas> Tarefas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipificacaoReal> TipificacaoReal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolumeProducao> VolumeProducao { get; set; }
    }
}
