//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_configuracao_email
    {
        public int id { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public string host { get; set; }
        public int port { get; set; }
    }
}
