//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pa_CausaMedidaXAcao
    {
        public int Id { get; set; }
        public Nullable<int> CausaGenerica_Id { get; set; }
        public Nullable<int> CausaEspecifica_Id { get; set; }
        public Nullable<int> ContramedidaGenerica_Id { get; set; }
        public Nullable<int> ContramedidaEspecifica_Id { get; set; }
        public Nullable<int> GrupoCausa_Id { get; set; }
        public int Acao_Id { get; set; }
    }
}
