//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_grupo_projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pa_grupo_projeto()
        {
            this.pa_projeto = new HashSet<pa_projeto>();
        }
    
        public string nome { get; set; }
        public int id { get; set; }
        public Nullable<int> sequencia { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual pa_empresa pa_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_projeto> pa_projeto { get; set; }
    }
}
