//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_log_operacao
    {
        public int id { get; set; }
        public string mensagem_operacao { get; set; }
        public Nullable<int> linha { get; set; }
        public string nm_usuario { get; set; }
        public Nullable<System.DateTime> dt_ocorrencia { get; set; }
        public Nullable<System.TimeSpan> hr_ocorrencia { get; set; }
        public Nullable<int> tp_registro { get; set; }
        public string tx_excecao { get; set; }
        public string dc_lan_ip { get; set; }
        public string tx_pilha_excecao { get; set; }
        public string dc_internet_ip { get; set; }
    }
}
