//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pa_projeto()
        {
            this.pa_campo = new HashSet<pa_campo>();
            this.pa_tarefa = new HashSet<pa_tarefa>();
            this.pa_vinculo_participante_projeto = new HashSet<pa_vinculo_participante_projeto>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public int id_empresa { get; set; }
        public Nullable<int> id_grupo_projeto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_campo> pa_campo { get; set; }
        public virtual pa_empresa pa_empresa { get; set; }
        public virtual pa_grupo_projeto pa_grupo_projeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_tarefa> pa_tarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_vinculo_participante_projeto> pa_vinculo_participante_projeto { get; set; }
    }
}
