//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_participante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pa_participante()
        {
            this.pa_tarefa = new HashSet<pa_tarefa>();
            this.pa_vinculo_campo_tarefa = new HashSet<pa_vinculo_campo_tarefa>();
            this.pa_vinculo_participante_multipla_escolha = new HashSet<pa_vinculo_participante_multipla_escolha>();
            this.pa_vinculo_participante_projeto = new HashSet<pa_vinculo_participante_projeto>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public bool ativo { get; set; }
        public int codigo { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public int id_empresa { get; set; }
        public Nullable<byte> perfil_acesso { get; set; }
    
        public virtual pa_empresa pa_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_tarefa> pa_tarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_vinculo_campo_tarefa> pa_vinculo_campo_tarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_vinculo_participante_multipla_escolha> pa_vinculo_participante_multipla_escolha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_vinculo_participante_projeto> pa_vinculo_participante_projeto { get; set; }
    }
}
