//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_tarefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pa_tarefa()
        {
            this.pa_acompanhamento_tarefa = new HashSet<pa_acompanhamento_tarefa>();
            this.pa_vinculo_campo_tarefa = new HashSet<pa_vinculo_campo_tarefa>();
        }
    
        public int id { get; set; }
        public int id_projeto { get; set; }
        public Nullable<int> id_participante_criador { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_acompanhamento_tarefa> pa_acompanhamento_tarefa { get; set; }
        public virtual pa_participante pa_participante { get; set; }
        public virtual pa_projeto pa_projeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pa_vinculo_campo_tarefa> pa_vinculo_campo_tarefa { get; set; }
    }
}
