//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pa_vinculo_campo_tarefa
    {
        public int id { get; set; }
        public Nullable<int> id_multipla_escolha { get; set; }
        public int id_campo { get; set; }
        public int id_tarefa { get; set; }
        public string valor { get; set; }
        public Nullable<int> id_participante { get; set; }
    
        public virtual pa_campo pa_campo { get; set; }
        public virtual pa_multipla_escolha pa_multipla_escolha { get; set; }
        public virtual pa_participante pa_participante { get; set; }
        public virtual pa_tarefa pa_tarefa { get; set; }
    }
}
