//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PadraoTolerancias
    {
        public int Id { get; set; }
        public int Monitoramento { get; set; }
        public Nullable<int> PadraoNivel1 { get; set; }
        public Nullable<int> PadraoNivel3 { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        public virtual Monitoramentos Monitoramentos { get; set; }
        public virtual Padroes Padroes { get; set; }
        public virtual Padroes Padroes1 { get; set; }
    }
}
