//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PadraoMonitoramentos
    {
        public int Id { get; set; }
        public int Padrao { get; set; }
        public int Monitoramento { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> Unidade { get; set; }
        public Nullable<int> UnidadeMedida { get; set; }
        public Nullable<int> UnidadeMedidaLegenda { get; set; }
        public string Tipo { get; set; }
    
        public virtual Monitoramentos Monitoramentos { get; set; }
        public virtual Padroes Padroes { get; set; }
        public virtual UnidadesMedidas UnidadesMedidas { get; set; }
        public virtual Unidades Unidades { get; set; }
        public virtual UnidadesMedidas UnidadesMedidas1 { get; set; }
    }
}
