//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;

    public partial class ParClusterXModule
    {
        public int Id { get; set; }
        public int ParCluster_Id { get; set; }
        public int ParModule_Id { get; set; }
        public decimal Points { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    
        public virtual ParCluster ParCluster { get; set; }
        public virtual ParModule ParModule { get; set; }
    }
}
