//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParCompanyXStructure
    {
        public int Id { get; set; }
        public int ParStructure_Id { get; set; }
        public int ParCompany_Id { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime AlterDate { get; set; }
        public bool Active { get; set; }
    
        public virtual ParCompany ParCompany { get; set; }
        public virtual ParStructure ParStructure { get; set; }
    }
}
