//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParGoal
    {
        public int Id { get; set; }
        public int ParLevel1_Id { get; set; }
        public int ParCompany_Id { get; set; }
        public decimal PercentValue { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public System.DateTime AlterDate { get; set; }
        public bool Active { get; set; }
    }
}
