//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParLevel1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParLevel1()
        {
            this.ParLevel1Cluster = new HashSet<ParLevel1Cluster>();
        }
    
        public int Id { get; set; }
        public int ParConsolidationType_Id { get; set; }
        public int ParFrequency_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool SaveLevel2 { get; set; }
        public bool NoApplicableLevel2 { get; set; }
        public bool GroupLevel2 { get; set; }
        public bool Alert { get; set; }
        public bool Specific { get; set; }
        public bool SpecificHeaderField { get; set; }
        public bool SpecificNumberEvaluetion { get; set; }
        public bool SpecificNumberSample { get; set; }
        public bool SpecificLevel3 { get; set; }
        public bool SpecificGoal { get; set; }
        public bool NonConformityRule { get; set; }
        public bool FixedEvaluetionNumber { get; set; }
        public bool LimitedEvaluetionNumber { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool Active { get; set; }
    
        public virtual ParConsolidationType ParConsolidationType { get; set; }
        public virtual ParFrequency ParFrequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParLevel1Cluster> ParLevel1Cluster { get; set; }
    }
}
