//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParLevel3Level2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParLevel3Level2()
        {
            this.ParLevel3Level2Level1 = new HashSet<ParLevel3Level2Level1>();
        }
    
        public int Id { get; set; }
        public int ParLevel2_Id { get; set; }
        public int ParLevel3_Id { get; set; }
        public Nullable<int> ParLevel3Group_Id { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ParCompany_Id { get; set; }
    
        public virtual ParLevel2 ParLevel2 { get; set; }
        public virtual ParLevel3 ParLevel3 { get; set; }
        public virtual ParLevel3Group ParLevel3Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParLevel3Level2Level1> ParLevel3Level2Level1 { get; set; }
        public virtual ParCompany ParCompany { get; set; }
    }
}
