//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParLevel1HeaderField
    {
        public int Id { get; set; }
        public int ParLevel1_Id { get; set; }
        public int ParHeaderField_Id { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ParHeaderField ParHeaderField { get; set; }
        public virtual ParLevel1 ParLevel1 { get; set; }
    }
}
