//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParNotConformityRuleXLevel
    {
        public Nullable<int> Id { get; set; }
        public int ParNotConformityRule_Id { get; set; }
        public Nullable<int> ParCompany_Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int Level { get; set; }
        public Nullable<int> ParLevel1_Id { get; set; }
        public Nullable<int> ParLevel2_Id { get; set; }
        public Nullable<int> ParLevel3_Id { get; set; }
        public Nullable<bool> IsReaudit { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool IsActive { get; set; }
    }
}
