//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoDeAcaoQuemQuandoComo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanoDeAcaoQuemQuandoComo()
        {
            this.fa_PlanoDeAcaoQuemQuandoComo = new HashSet<fa_PlanoDeAcaoQuemQuandoComo>();
        }
    
        public int Id { get; set; }
        public string Quem { get; set; }
        public System.DateTime Quando { get; set; }
        public string Como { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_PlanoDeAcaoQuemQuandoComo> fa_PlanoDeAcaoQuemQuandoComo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
