//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuerySgq
    {
        public int Id { get; set; }
        public string Query { get; set; }
        public string Desc { get; set; }
        public string FastKey { get; set; }
        public bool IsActive { get; set; }
    }
}
