//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports_HTP_Audit
    {
        public Nullable<int> Plant_Number { get; set; }
        public int Shift { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public string Start_Time { get; set; }
        public string Job_Id { get; set; }
        public string Auditor { get; set; }
        public string Audit_ReAudit { get; set; }
        public int Period { get; set; }
        public string Baised_Unbiased { get; set; }
        public Nullable<System.DateTime> Job_Date { get; set; }
        public string Job_Time { get; set; }
        public int Starting_Phase { get; set; }
        public string Core_Practice_HTP_Deviation { get; set; }
        public string Other_Deviaton { get; set; }
        public Nullable<int> Ending_Phase { get; set; }
        public string Reaudit { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string End_Time { get; set; }
        public int ID { get; set; }
    }
}
