//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports_CCA_Audit
    {
        public Nullable<int> Plant_Number { get; set; }
        public string Audit_Area { get; set; }
        public Nullable<System.DateTime> Set_Start_Date { get; set; }
        public string Set_Start_Time { get; set; }
        public int Audit_Period { get; set; }
        public int Shift { get; set; }
        public string Audit_Reaudit { get; set; }
        public Nullable<decimal> Specks { get; set; }
        public Nullable<decimal> Dressing { get; set; }
        public Nullable<decimal> Single_Hairs { get; set; }
        public Nullable<decimal> Clusters { get; set; }
        public Nullable<decimal> Hide { get; set; }
        public Nullable<decimal> Defects { get; set; }
        public string No_of_Def { get; set; }
        public string Cattle_Type { get; set; }
        public decimal Chain_Speed { get; set; }
        public decimal Lot__ { get; set; }
        public decimal Mud_Score { get; set; }
        public string Auditor_Name_Global { get; set; }
        public Nullable<System.DateTime> Set_End_Date { get; set; }
        public string Set_End_Time { get; set; }
    }
}
