//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultLevel2HeaderField
    {
        public int Id { get; set; }
        public int CollectionLevel2_Id { get; set; }
        public int ParHeaderField_Id { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public Nullable<decimal> PunishmentValue { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public bool IsActive { get; set; }
    }
}
