//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosData
    {
        public int Id { get; set; }
        public string Chave { get; set; }
        public string Campo { get; set; }
        public System.DateTime Valor { get; set; }
    }
}
