//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosPCC
    {
        public int Id { get; set; }
        public string Chave { get; set; }
        public int EmpresaId { get; set; }
        public string Empresa { get; set; }
        public int UnidadeId { get; set; }
        public string Unidade { get; set; }
        public int DepartamentoId { get; set; }
        public string Departamento { get; set; }
        public int OperacaoId { get; set; }
        public string Operacao { get; set; }
        public int TarefaId { get; set; }
        public string Tarefa { get; set; }
        public int NumeroAvaliacao { get; set; }
        public int NumeroAmostra { get; set; }
        public int MonitoramentoId { get; set; }
        public string Monitoramento { get; set; }
        public int ProdutoId { get; set; }
        public string Produto { get; set; }
        public System.DateTime DataHora { get; set; }
        public int Monitor { get; set; }
        public Nullable<int> Peso { get; set; }
        public string Lote { get; set; }
        public Nullable<int> PecasAvaliadas { get; set; }
        public string Minimo { get; set; }
        public string Maximo { get; set; }
        public string Acesso { get; set; }
        public string Avaliacao_1 { get; set; }
        public int Avaliacao_2 { get; set; }
        public Nullable<decimal> Meta { get; set; }
        public Nullable<int> Sequencial { get; set; }
        public Nullable<int> Banda { get; set; }
        public Nullable<System.DateTime> DataHoraMonitor { get; set; }
        public Nullable<int> ToleranciaDia { get; set; }
        public Nullable<int> Nivel1 { get; set; }
        public Nullable<int> Nivel2 { get; set; }
        public Nullable<int> Nivel3 { get; set; }
        public string Status { get; set; }
        public Nullable<bool> AvaliacaoAvulsa { get; set; }
        public string Amostragem { get; set; }
        public string FormaAmostragem { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Idade { get; set; }
        public string SiglaContusao { get; set; }
        public string SiglaFalhaOperacional { get; set; }
        public Nullable<System.DateTime> DataTipificacao { get; set; }
        public Nullable<bool> Mobile { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Identificador { get; set; }
        public string VersaoAPP { get; set; }
    }
}
