//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScorecardConsolidadoDia
    {
        public int Unidade { get; set; }
        public int Operacao { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<decimal> TotalAvaliado { get; set; }
        public Nullable<decimal> TotalForaPadrao { get; set; }
        public Nullable<decimal> Meta { get; set; }
        public Nullable<decimal> Pontos { get; set; }
    }
}
