//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarefas()
        {
            this.AcoesCorretivas = new HashSet<AcoesCorretivas>();
            this.Alertas = new HashSet<Alertas>();
            this.MonitoramentosConcorrentes = new HashSet<MonitoramentosConcorrentes>();
            this.ObservacoesPadroes = new HashSet<ObservacoesPadroes>();
            this.TarefaAmostras = new HashSet<TarefaAmostras>();
            this.TarefaAvaliacoes = new HashSet<TarefaAvaliacoes>();
            this.TarefaCategorias = new HashSet<TarefaCategorias>();
            this.TarefaMonitoramentos = new HashSet<TarefaMonitoramentos>();
        }
    
        public int Id { get; set; }
        public int Operacao { get; set; }
        public string Nome { get; set; }
        public string Amostragem { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> Departamento { get; set; }
        public string Frequencia { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public Nullable<int> Produto { get; set; }
        public Nullable<bool> EditarAcesso { get; set; }
        public Nullable<bool> ExibirAcesso { get; set; }
        public string FormaAmostragem { get; set; }
        public Nullable<bool> AvaliarProdutos { get; set; }
        public Nullable<int> Sequencial { get; set; }
        public Nullable<bool> InformarPesagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcoesCorretivas> AcoesCorretivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alertas> Alertas { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoramentosConcorrentes> MonitoramentosConcorrentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacoesPadroes> ObservacoesPadroes { get; set; }
        public virtual Operacoes Operacoes { get; set; }
        public virtual Produtos Produtos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaAmostras> TarefaAmostras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaAvaliacoes> TarefaAvaliacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaCategorias> TarefaCategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaMonitoramentos> TarefaMonitoramentos { get; set; }
    }
}
