//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificacaoTipificacaoTarefaIntegracao
    {
        public int Id { get; set; }
        public int TarefaId { get; set; }
        public int CaracteristicaTipificacaoId { get; set; }
    
        public virtual Monitoramentos Monitoramentos { get; set; }
    }
}
