//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificacaoTipificacao
    {
        public int Id { get; set; }
        public int Sequencial { get; set; }
        public byte Banda { get; set; }
        public System.DateTime DataHora { get; set; }
        public int UnidadeId { get; set; }
        public string Chave { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
