//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolumeProducao
    {
        public int Id { get; set; }
        public int Operacao { get; set; }
        public int Unidade { get; set; }
        public System.DateTime Data { get; set; }
        public int Departamento { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> Quartos { get; set; }
        public Nullable<decimal> Meta { get; set; }
        public Nullable<decimal> ToleranciaDia { get; set; }
        public Nullable<decimal> Nivel1 { get; set; }
        public Nullable<decimal> Nivel2 { get; set; }
        public Nullable<decimal> Nivel3 { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<int> HorasTrabalho { get; set; }
        public Nullable<int> QuantidadeMediaHora { get; set; }
        public Nullable<int> NivelGeralInspecao { get; set; }
        public Nullable<int> AvaliacaoHora { get; set; }
        public Nullable<int> QtdColabOuEsteiras { get; set; }
        public Nullable<int> QuantidadeAvaliacao { get; set; }
        public Nullable<int> TamanhoAmostra { get; set; }
        public Nullable<int> AmostraAvaliacao { get; set; }
        public Nullable<int> AmostraDia { get; set; }
        public Nullable<int> QtdFamiliaProdutos { get; set; }
        public int UsuarioInsercao { get; set; }
        public System.DateTime DataInsercao { get; set; }
        public Nullable<int> UsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Operacoes Operacoes { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
