//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTVerificacaoTipificacaoJBS
    {
        public int nCdEmpresa { get; set; }
        public Nullable<System.DateTime> dMovimento { get; set; }
        public int iSequencial { get; set; }
        public int iSequencialTipificacao { get; set; }
        public int iBanda { get; set; }
        public string cIdentificadorTipificacao { get; set; }
        public int nCdCaracteristicaTipificacao { get; set; }
    }
}
