//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCFFResults
    {
        public Nullable<int> Plant_Number { get; set; }
        public int Shift { get; set; }
        public int Period { get; set; }
        public Nullable<int> Set { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public int Side { get; set; }
        public string Audit_Area { get; set; }
        public Nullable<System.DateTime> Set_Start_Date { get; set; }
        public string Set_Start_Time { get; set; }
        public Nullable<System.DateTime> Set_End_Date { get; set; }
        public string Set_End_Time { get; set; }
        public string Auditor { get; set; }
        public string Reaudit { get; set; }
        public Nullable<decimal> Defects { get; set; }
        public Nullable<decimal> Cut { get; set; }
        public Nullable<decimal> Fold_Flap { get; set; }
        public Nullable<decimal> Puncture { get; set; }
        public int Defect_Counter { get; set; }
    }
}
