//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoAcaoEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanoDeAcaoEntities : DbContext
    {
        public PlanoDeAcaoEntities()
            : base("name=PlanoDeAcaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pa_Acao> Pa_Acao { get; set; }
        public virtual DbSet<Pa_Acompanhamento> Pa_Acompanhamento { get; set; }
        public virtual DbSet<Pa_AcompanhamentoXQuem> Pa_AcompanhamentoXQuem { get; set; }
        public virtual DbSet<Pa_FTA> Pa_FTA { get; set; }
        public virtual DbSet<Pa_Planejamento> Pa_Planejamento { get; set; }
    }
}
