//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoAcaoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pa_AcompanhamentoXQuem
    {
        public int Id { get; set; }
        public int Acompanhamento_Id { get; set; }
        public int Quem_Id { get; set; }
    }
}
