//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanoAcaoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pa_Planejamento
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public Nullable<int> Diretoria_Id { get; set; }
        public Nullable<int> Gerencia_Id { get; set; }
        public Nullable<int> Coordenacao_Id { get; set; }
        public Nullable<int> Missao_Id { get; set; }
        public Nullable<int> Visao_Id { get; set; }
        public Nullable<int> TemaAssunto_Id { get; set; }
        public Nullable<int> Indicadores_Id { get; set; }
        public Nullable<int> Iniciativa_Id { get; set; }
        public Nullable<int> ObjetivoGerencial_Id { get; set; }
        public string Dimensao { get; set; }
        public string Objetivo { get; set; }
        public Nullable<decimal> ValorDe { get; set; }
        public Nullable<decimal> ValorPara { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Dimensao_Id { get; set; }
        public Nullable<int> Objetivo_Id { get; set; }
        public Nullable<int> IndicadoresDiretriz_Id { get; set; }
        public Nullable<int> IndicadoresDeProjeto_Id { get; set; }
        public Nullable<int> Estrategico_Id { get; set; }
        public Nullable<int> Responsavel_Diretriz { get; set; }
        public Nullable<int> Responsavel_Projeto { get; set; }
        public Nullable<int> UnidadeDeMedida_Id { get; set; }
        public bool IsTatico { get; set; }
        public Nullable<int> Tatico_Id { get; set; }
        public Nullable<bool> IsFta { get; set; }
    }
}
